let wordTrie = WordTrie()
wordTrie.add(word: "tree")
wordTrie.add(word: "tea")
wordTrie.add(word: "tiny")
wordTrie.add(word: "telescope")
wordTrie.add(word: "bird")
print(":", wordTrie.findCompletions(word: ""))
print("t:", wordTrie.findCompletions(word: "t"))
print("b:", wordTrie.findCompletions(word: "b"))
print("te:", wordTrie.findCompletions(word: "te"))